# defaults:

io_dir:
  data_dir: ..\data
  config_dir: .\configs
  results_dir: .\results
  cfe_dir: ..\cfe_py
  model_config_dir: ..\data\model_common_configs
  camels_dir: ..\data\camels
  gauch_2020_dir: ..\data\camels\gauch_etal_2020
  ucar_dir: ..\data\camels\ucar
  usgs_streamflow_dir: ..\data\camels\gauch_etal_2020\usgs_streamflow
  ncar_forcing_dir: ..\data\camels\gauch_etal_2020\nldas_hourly
  basin_dir: ..\data\camels\gauch_etal_2020

model_settings:
  basin_file: ..\data\camels\gauch_etal_2020\basin_list_516.txt
  missing_data_file: ..\data\camels\gauch_etal_2020\basin_list_missing_data_v2023.txt
  time_split_file: ..\data\model_common_configs\cal-val-test-period.json
  parameter_bound_file: ..\data\model_common_configs\CFE_parameter_bounds.json


############## calibration settings ############
calib_variables:
  N: 10
  max_nbasin_per_loop: 1
  print_all_process: False
