name: CFE
channels:
  - conda-forge
  - defaults

dependencies:
  - python
  - numpy
  - scipy
  - pandas
  - jupyterlab
  - netCDF4
  - scikit-learn
  - scikit-fuzzy
  - geopandas
  - xarray
  - matplotlib
  - seaborn
  - spotpy
  - yaml
  - tqdm
  - pip
  - pip:
    - hydra-core
    - hydroeval
    - hsclient
    - wget