hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  launcher:
    _target_: hydra_plugins.hydra_joblib_launcher.joblib_launcher.JoblibLauncher
    n_jobs: -1
    backend: null
    prefer: processes
    require: null
    verbose: 0
    timeout: null
    pre_dispatch: 2*n_jobs
    batch_size: auto
    temp_folder: null
    max_nbytes: null
    mmap_mode: r
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: .hydra
  overrides:
    hydra:
    - hydra.mode=MULTIRUN
    task:
    - basin_id=01022500,01031500,01047000,01052500,01054200
  job:
    name: 3-CFE_Calibration_Loop_1
    chdir: null
    override_dirname: basin_id=01022500,01031500,01047000,01052500,01054200
    id: ???
    num: ???
    config_name: config
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.3.2
    version_base: '1.3'
    cwd: /scratch/sbhuiya2/SI2023/calibrate-cfe
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /scratch/sbhuiya2/SI2023/calibrate-cfe
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: joblib
      hydra/output: default
  verbose: false
cwd: /scratch/sbhuiya2/SI2023
io_dir:
  data_dir: ${cwd}/data
  config_dir: ${cwd}/calibrate-cfe/configs
  results_dir: ${cwd}/calibrate-cfe/results
  cfe_dir: ${cwd}/cfe_py
  model_config_dir: ${cwd}/data/model_common_configs
  camels_dir: ${cwd}/data/camels
  gauch_2020_dir: ${cwd}/data/camels/gauch_etal_2020
  ucar_dir: ${cwd}/data/camels/ucar
  usgs_streamflow_dir: ${cwd}/data/camels/gauch_etal_2020/usgs_streamflow
  nldas_forcing_dir: ${cwd}/data/camels/gauch_etal_2020/nldas_hourly
  basin_dir: ${cwd}/data/camels/gauch_etal_2020
model_settings:
  basin_file: ${cwd}/data/camels/gauch_etal_2020/basin_list_5.txt
  missing_data_file: ${cwd}/data/camels/gauch_etal_2020/basin_list_missing_data.txt
  time_split_file: ${cwd}/data/model_common_configs/cal-val-test-period.json
  parameter_bound_file: ${cwd}/data/model_common_configs/CFE_parameter_bounds.json
calib_variables:
  'N': 10
  max_nbasin_per_loop: 1
  print_all_process: false
basin_id: ???
